CC = g++
CFLAGS = -std=c++11 -Wall
SOURCEFILES = ./Snaaakeecpp/Snaaakeecpp.cpp ./Snaaakeecpp/Snake.cpp ./Snaaakeecpp/Input.cpp ./Snaaakeecpp/Path.cpp ./Snaaakeecpp/Grid.cpp ./Snaaakeecpp/Display.cpp ./Snaaakeecpp/Game.cpp

SNAAAKEE: $(SOURCEFILES)
	$(CC) $(CFLAGS) $(SOURCEFILES) -o ./Snaaakee.o
